USE PAYROLL;
DESC EMPLOYEE;
DESC DEPARTMENT;
DESC DESIGNATION;
DESC ATTENDANCE;
DESC BONUS;
DESC BASIC_SALARY;

SELECT E.EMP_ID,E.EMPLOYEE_NAME,D.DEPARTMENT_NAME, DE.DESIGNATION, B.SALARY FROM EMPLOYEE E INNER JOIN 
DEPARTMENT D ON D.DEPT_ID=E.DEPT_ID
INNER JOIN DESIGNATION DE ON D.DEPT_ID=DE.DEPT_ID && E.DESIGNATION_ID=DE.DESIGNATION_ID
INNER JOIN BASIC_SALARY B ON B.DEPT_ID=D.DEPT_ID && B.DESIGNATION_ID=DE.DESIGNATION_ID
WHERE E.EMP_ID < 4;


DESC PAYROLL_REPORT;
INSERT INTO PAYROLL_REPORT(EMP_ID,DEPT_ID,DESINATION_ID,SALARY_ID,BONUS_ID,TOTAL_PAY)
SELECT E.EMP_ID,D.DEPT_ID,DE.DESIGNATION_ID,BS.SALARY_ID,B.BONUS_ID,BS.SALARY+B.AMOUNT
FROM  EMPLOYEE E
INNER JOIN DEPARTMENT D ON E.DEPT_ID=D.DEPT_ID
INNER JOIN DESIGNATION DE ON DE.DEPT_ID=D.DEPT_ID && DE.DESIGNATION_ID=E.DESIGNATION_ID
INNER JOIN BASIC_SALARY BS ON BS.DEPT_ID=D.DEPT_ID && BS.DESIGNATION_ID=DE.DESIGNATION_ID
INNER JOIN BONUS B ON B.EMP_ID=E.EMP_ID
WHERE E.EMP_ID=1;

SELECT * FROM PAYROLL_REPORT;

SELECT E.EMP_ID,E.EMPLOYEE_NAME,D.DEPARTMENT_NAME, DE.DESIGNATION, B.SALARY FROM EMPLOYEE E INNER JOIN 
DEPARTMENT D ON D.DEPT_ID=E.DEPT_ID
INNER JOIN DESIGNATION DE ON D.DEPT_ID=DE.DEPT_ID && E.DESIGNATION_ID=DE.DESIGNATION_ID
INNER JOIN BASIC_SALARY B ON B.DEPT_ID=D.DEPT_ID && B.DESIGNATION_ID=DE.DESIGNATION_ID
ORDER BY B.SALARY DESC;

SELECT E.EMP_ID,E.EMPLOYEE_NAME,D.DEPARTMENT_NAME, DE.DESIGNATION, B.SALARY FROM EMPLOYEE E 
INNER JOIN DEPARTMENT D ON D.DEPT_ID=E.DEPT_ID
INNER JOIN DESIGNATION DE ON D.DEPT_ID=DE.DEPT_ID && E.DESIGNATION_ID=DE.DESIGNATION_ID
INNER JOIN BASIC_SALARY B ON B.DEPT_ID=D.DEPT_ID && B.DESIGNATION_ID=DE.DESIGNATION_ID
WHERE NOT (D.DEPT_ID='A3302' OR DE.DESIGNATION_ID='TL_001');

-- ALTER TABLE DEPARTMENT MODIFY COLUMN CONTACT

SELECT * FROM ATTENDANCE WHERE EMP_ID=5;
UPDATE ATTENDANCE SET ABSENTS=5 WHERE EMP_ID=5 AND WORKING_MONTH='JUNE';
SELECT * FROM ATTENDANCE WHERE EMP_ID=5;


SELECT E.EMP_ID,E.EMPLOYEE_NAME,D.DEPARTMENT_NAME, DE.DESIGNATION, B.SALARY FROM EMPLOYEE E INNER JOIN 
DEPARTMENT D ON D.DEPT_ID=E.DEPT_ID
INNER JOIN DESIGNATION DE ON D.DEPT_ID=DE.DEPT_ID && E.DESIGNATION_ID=DE.DESIGNATION_ID
INNER JOIN BASIC_SALARY B ON B.DEPT_ID=D.DEPT_ID && B.DESIGNATION_ID=DE.DESIGNATION_ID
ORDER BY B.SALARY DESC;

SELECT MAX(SALARY), MIN(SALARY) FROM BASIC_SALARY;

SELECT D.DEPARTMENT_NAME, COUNT(DE.DESIGNATION_ID) AS 'NO. OF DESIGNATIONS' FROM DEPARTMENT D
INNER JOIN DESIGNATION DE ON D.DEPT_ID=DE.DEPT_ID
GROUP BY D.DEPT_ID;

SELECT AVG(SALARY) FROM BASIC_SALARY;

SELECT SUM(SALARY) FROM BASIC_SALARY;


SELECT E.EMP_ID,E.EMPLOYEE_NAME,D.DEPARTMENT_NAME, DE.DESIGNATION, B.SALARY FROM EMPLOYEE E INNER JOIN 
DEPARTMENT D ON D.DEPT_ID=E.DEPT_ID
INNER JOIN DESIGNATION DE ON D.DEPT_ID=DE.DEPT_ID && E.DESIGNATION_ID=DE.DESIGNATION_ID
INNER JOIN BASIC_SALARY B ON B.DEPT_ID=D.DEPT_ID && B.DESIGNATION_ID=DE.DESIGNATION_ID
WHERE E.EMPLOYEE_NAME LIKE 'A%';


SELECT E.EMP_ID,E.EMPLOYEE_NAME,D.DEPARTMENT_NAME, DE.DESIGNATION, B.SALARY FROM EMPLOYEE E INNER JOIN 
DEPARTMENT D ON D.DEPT_ID=E.DEPT_ID
INNER JOIN DESIGNATION DE ON D.DEPT_ID=DE.DEPT_ID && E.DESIGNATION_ID=DE.DESIGNATION_ID
INNER JOIN BASIC_SALARY B ON B.DEPT_ID=D.DEPT_ID && B.DESIGNATION_ID=DE.DESIGNATION_ID
GROUP BY D.DEPT_ID
HAVING COUNT(DE.DESIGNATION_ID)>3;


SELECT E.EMP_ID,E.EMPLOYEE_NAME,D.DEPARTMENT_NAME, DE.DESIGNATION, B.SALARY FROM EMPLOYEE E INNER JOIN 
DEPARTMENT D ON D.DEPT_ID=E.DEPT_ID
INNER JOIN DESIGNATION DE ON D.DEPT_ID=DE.DEPT_ID && E.DESIGNATION_ID=DE.DESIGNATION_ID
INNER JOIN BASIC_SALARY B ON B.DEPT_ID=D.DEPT_ID && B.DESIGNATION_ID=DE.DESIGNATION_ID
WHERE EXISTS(SELECT ABSENTS FROM ATTENDANCE WHERE E.EMP_ID=ATTENDANCE.EMP_ID AND ABSENTS > 5);

ALTER TABLE EMPLOYEE ADD ELIGIBLE_FOR_VOTE VARCHAR(3) DEFAULT 'YES';
DESC EMPLOYEE;

CREATE index EMP
ON EMPLOYEE(EMP_ID);

CREATE VIEW `NAME STARTING WITH A` AS
SELECT E.EMP_ID,E.EMPLOYEE_NAME,D.DEPARTMENT_NAME, DE.DESIGNATION, B.SALARY FROM EMPLOYEE E INNER JOIN 
DEPARTMENT D ON D.DEPT_ID=E.DEPT_ID
INNER JOIN DESIGNATION DE ON D.DEPT_ID=DE.DEPT_ID && E.DESIGNATION_ID=DE.DESIGNATION_ID
INNER JOIN BASIC_SALARY B ON B.DEPT_ID=D.DEPT_ID && B.DESIGNATION_ID=DE.DESIGNATION_ID
WHERE E.EMPLOYEE_NAME LIKE 'A%';
SELECT * FROM `NAME STARTING WITH A`;


